title: 酱油先生 Blog
author: ijackwu
email: ijackwu365@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  记录工作学习中遇到问题，好记性不如烂笔头，记录经常出现的问题，
  总结记录解决方法加深记忆，避免每次google浪费时间。


github_username:  ijackwu

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"



lang: zh-CN

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

# Disqus
disqus:
  shortname: ijackwu
